### ISSUE TITLE
Are these the 42 instances of Clautiaux?

### ISSUE THREAD

**Issue by henriquebecker91** [denisnsc/caparf#5]
Sorry to bother you, but I would like to confirm the file: https://github.com/denisnsc/caparf/blob/4cc96a73af9cc00aec748aca16a5ad3bda2719fe/src/com/googlecode/caparf/inputs/opp2d/ClautiauxReferenceInstances.txt has the exact 42 instances that Clautiaux introduces on "A new exact method for the two-dimensional orthogonal packing problem" (https://doi.org/10.1016/j.ejor.2005.12.048). I am having problems to find a repository that lists such instances and do not have a broken link.

**Comment by denisnsc** [comment]
These are the instances from https://doi.org/10.1016/j.ejor.2005.12.048 inroduced by Clautiaux to the best of my knowledge.
